<?php

namespace Database\Seeders;

use App\Models\Generation;
use App\Models\Member;
use Illuminate\Database\Seeder;

class MemberSeeder extends Seeder
{
    public function run(): void
    {
        $genMap = Generation::pluck('id', 'code')->toArray();

        $members = [

            // Generasi 1
            ['name' => 'Alissa Galliamova', 'nickname' => 'Mova', 'birth_place' => 'Bandung', 'birth_date' => '1993-08-28', 'gen' => '1', 'join_date' => '2011-11-02', 'status' => 'Lulus', 'promotion_date' => '2012-12-23', 'graduation_date' => '2013-01-16', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Allisa Astri', 'nickname' => 'Icha', 'birth_place' => '', 'birth_date' => '1990-06-23', 'gen' => '1', 'join_date' => '2011-11-02', 'status' => 'Lulus', 'graduation_date' => '2012-05-10', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Ayana Shahab', 'nickname' => 'Ayana', 'birth_place' => 'Osaka', 'birth_date' => '1997-06-03', 'gen' => '1', 'join_date' => '2011-11-02', 'status' => 'Lulus', 'promotion_date' => '2012-12-23', 'graduation_announce_date' => '2019-06-16', 'graduation_announce_event' => 'Sambil Menggandeng Erat Tanganku', 'graduation_date' => '2019-12-08', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Beby Chaesara Anadila', 'nickname' => 'Beby', 'birth_place' => 'Bandung', 'birth_date' => '1998-03-18', 'gen' => '1', 'join_date' => '2011-11-02', 'status' => 'Lulus', 'promotion_date' => '2012-12-23', 'graduation_announce_date' => '2019-12-22', 'graduation_announce_event' => 'JKT48 8th Anniversary Concert', 'graduation_date' => '2021-02-21', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Cindy Gulla', 'nickname' => 'Cindy', 'birth_place' => 'Jakarta', 'birth_date' => '1997-05-29', 'gen' => '1', 'join_date' => '2011-11-02', 'status' => 'Lulus', 'promotion_date' => '2012-12-23', 'graduation_date' => '2014-02-16', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Cleopatra Djapri', 'nickname' => 'Cleo', 'birth_place' => 'Jakarta', 'birth_date' => '1993-12-20', 'gen' => '1', 'join_date' => '2011-11-02', 'status' => 'Lulus', 'graduation_date' => '2012-12-10', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Delima Rizky', 'nickname' => 'Delima', 'birth_place' => 'Bogor', 'birth_date' => '1997-10-25', 'gen' => '1', 'join_date' => '2011-11-02', 'status' => 'Lulus', 'promotion_date' => '2012-12-23', 'graduation_date' => '2016-03-18', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Devi Kinal Putri', 'nickname' => 'Kinal', 'birth_place' => 'Bandung', 'birth_date' => '1996-01-02', 'gen' => '1', 'join_date' => '2011-11-02', 'status' => 'Lulus', 'promotion_date' => '2012-12-23', 'graduation_announce_date' => '2018-03-25', 'graduation_announce_event' => 'Kimi wa Melody Handshake', 'graduation_date' => '2018-06-30', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Diasta Priswarini', 'nickname' => 'Diasta', 'birth_place' => 'Bandung', 'birth_date' => '1991-09-09', 'gen' => '1', 'join_date' => '2011-11-02', 'status' => 'Lulus', 'promotion_date' => '2012-12-23', 'graduation_announce_date' => '2013-11-21', 'graduation_announce_event' => 'Aturan Anti Cinta', 'graduation_date' => '2013-12-22', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Fahira', 'nickname' => 'Fahira', 'birth_place' => '', 'birth_date' => '1998-07-27', 'gen' => '1', 'join_date' => '2011-11-02', 'status' => 'Lulus', 'graduation_date' => '2012-05-10', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Frieska Anastasia Laksani', 'nickname' => 'Frieska', 'birth_place' => 'Bandung', 'birth_date' => '1996-03-04', 'gen' => '1', 'join_date' => '2011-11-02', 'status' => 'Lulus', 'promotion_date' => '2012-12-23', 'graduation_announce_date' => '2020-11-17', 'graduation_announce_event' => 'Fajar Sang Idola', 'graduation_date' => '2021-02-20', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Gabriela Margareth Warouw', 'nickname' => 'Gaby', 'birth_place' => 'Jakarta', 'birth_date' => '1998-04-11', 'gen' => '1', 'join_date' => '2011-11-02', 'status' => 'Lulus', 'promotion_date' => '2012-12-23', 'graduation_announce_date' => '2021-12-18', 'graduation_announce_event' => 'JKT48 10th Anniversary Kick Off Conference', 'graduation_date' => '2022-08-14', 'restructure_status' => 'Lulus Setelah Restrukturisasi'],
            ['name' => 'Ghaida Farisya', 'nickname' => 'Ghaida', 'birth_place' => 'Pandeglang', 'birth_date' => '1995-05-29', 'gen' => '1', 'join_date' => '2011-11-02', 'status' => 'Lulus', 'promotion_date' => '2012-12-23', 'graduation_announce_date' => '2016-10-23', 'graduation_announce_event' => 'Dewi Theater', 'graduation_date' => '2016-11-20', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Intania Pratama Ilham', 'nickname' => 'Intania', 'birth_place' => '', 'birth_date' => '1991-07-19', 'gen' => '1', 'join_date' => '2011-11-02', 'status' => 'Lulus', 'graduation_date' => '2012-02-12', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Jessica Vania', 'nickname' => 'Jeje', 'birth_place' => 'Jakarta', 'birth_date' => '1996-01-22', 'gen' => '1', 'join_date' => '2011-11-02', 'status' => 'Lulus', 'promotion_date' => '2012-12-23', 'graduation_announce_date' => '2017-01-26', 'graduation_announce_event' => 'Team J B•E•L•I•E•V•E Show', 'graduation_date' => '2017-03-12', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Jessica Veranda Tanumihardja', 'nickname' => 'Veranda', 'birth_place' => 'Jakarta', 'birth_date' => '1993-08-19', 'gen' => '1', 'join_date' => '2011-11-02', 'status' => 'Lulus', 'promotion_date' => '2012-12-23', 'graduation_announce_date' => '2017-03-04', 'graduation_announce_event' => 'Team J B•E•L•I•E•V•E Show', 'graduation_date' => '2017-05-25', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Melody Nurramdhani Laksani', 'nickname' => 'Melody', 'birth_place' => 'Bandung', 'birth_date' => '1992-03-24', 'gen' => '1', 'join_date' => '2011-11-02', 'status' => 'Lulus', 'promotion_date' => '2012-12-23', 'graduation_announce_date' => '2017-11-04', 'graduation_announce_event' => 'JKT48 Request Hour Setlist Best 30 2017', 'graduation_date' => '2018-03-31', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Nabilah Ratna Ayu Azalia', 'nickname' => 'Nabilah', 'birth_place' => 'Jakarta', 'birth_date' => '1999-11-11', 'gen' => '1', 'join_date' => '2011-11-02', 'status' => 'Lulus', 'promotion_date' => '2012-12-23', 'graduation_date' => '2017-10-31', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Neneng Rosediana', 'nickname' => 'Ochi', 'birth_place' => 'Lebak', 'birth_date' => '1999-01-24', 'gen' => '1', 'join_date' => '2011-11-02', 'status' => 'Lulus', 'graduation_date' => '2012-11-25', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Rena Nozawa', 'nickname' => 'Rena', 'birth_place' => 'Nagoya', 'birth_date' => '1998-05-06', 'gen' => '1', 'join_date' => '2011-11-02', 'status' => 'Lulus', 'promotion_date' => '2012-12-23', 'graduation_date' => '2014-04-24', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Rezky Wiranti Dhike', 'nickname' => 'Dhike', 'birth_place' => 'Kepahiang', 'birth_date' => '1995-11-22', 'gen' => '1', 'join_date' => '2011-11-02', 'status' => 'Lulus', 'promotion_date' => '2012-12-23', 'graduation_announce_date' => '2016-07-14', 'graduation_announce_event' => 'Dewi Theater', 'graduation_date' => '2016-09-13', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Rica Leyona', 'nickname' => 'Rica', 'birth_place' => 'Bogor', 'birth_date' => '1991-08-19', 'gen' => '1', 'join_date' => '2011-11-02', 'status' => 'Lulus', 'promotion_date' => '2012-12-23', 'graduation_date' => '2014-12-04', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Sendy Ariani', 'nickname' => 'Sendy', 'birth_place' => 'Bogor', 'birth_date' => '1993-08-12', 'gen' => '1', 'join_date' => '2011-11-02', 'status' => 'Lulus', 'promotion_date' => '2012-12-23', 'graduation_date' => '2016-12-01', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Shania Junianatha', 'nickname' => 'Shanju', 'birth_place' => 'Solo', 'birth_date' => '1998-06-27', 'gen' => '1', 'join_date' => '2011-11-02', 'status' => 'Lulus', 'promotion_date' => '2012-12-23', 'graduation_announce_date' => '2018-11-17', 'graduation_announce_event' => 'Event Pengumuman Hasil Pemilihan Member Single ke-20 JKT48 & Pre-Event Live Concert', 'graduation_date' => '2019-04-28', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Siti Gayatri Abhirama', 'nickname' => 'Gayatri', 'birth_place' => '', 'birth_date' => '1993-03-11', 'gen' => '1', 'join_date' => '2011-11-02', 'status' => 'Lulus', 'graduation_date' => '2012-02-12', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Sonia Natalia', 'nickname' => 'Sonia', 'birth_place' => 'Semarang', 'birth_date' => '1997-12-17', 'gen' => '1', 'join_date' => '2011-11-02', 'status' => 'Lulus', 'promotion_date' => '2012-12-23', 'graduation_announce_date' => '2019-08-17', 'graduation_announce_event' => 'Sambil Menggandeng Erat Tanganku', 'graduation_date' => '2019-12-07', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Sonya Pandarmawan', 'nickname' => 'Sonya', 'birth_place' => 'Jakarta', 'birth_date' => '1996-05-18', 'gen' => '1', 'join_date' => '2011-11-02', 'status' => 'Lulus', 'promotion_date' => '2012-12-23', 'graduation_announce_date' => '2013-11-21', 'graduation_announce_event' => 'Aturan Anti Cinta', 'graduation_date' => '2013-12-22', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Stella Cornelia', 'nickname' => 'Stella', 'birth_place' => 'Semarang', 'birth_date' => '1994-11-03', 'gen' => '1', 'join_date' => '2011-11-02', 'status' => 'Lulus', 'promotion_date' => '2012-12-23', 'graduation_announce_date' => '2013-11-03', 'graduation_announce_event' => 'Aturan Anti Cinta', 'graduation_date' => '2013-12-28', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],

            // Generasi 2
            ['name' => 'Alicia Chanzia', 'nickname' => 'Acha', 'birth_place' => 'Bandung', 'birth_date' => '1999-05-24', 'gen' => '2', 'join_date' => '2012-11-03', 'status' => 'Lulus', 'promotion_date' => '2013-06-25', 'graduation_announce_date' => '2019-04-30', 'graduation_announce_event' => 'Romansa Sang Gadis', 'graduation_date' => '2019-08-04', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Althea Callista', 'nickname' => 'Althea', 'birth_place' => 'Jakarta', 'birth_date' => '1997-07-11', 'gen' => '2', 'join_date' => '2012-11-03', 'status' => 'Lulus', 'graduation_date' => '2013-01-10', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Annisa Athia', 'nickname' => 'Nisa', 'birth_place' => '', 'birth_date' => '1997-10-08', 'gen' => '2', 'join_date' => '2012-11-03', 'status' => 'Lulus', 'graduation_date' => '2013-09-09', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Cindy Yuvia', 'nickname' => 'Yupi', 'birth_place' => 'Jakarta', 'birth_date' => '1998-01-14', 'gen' => '2', 'join_date' => '2012-11-03', 'status' => 'Lulus', 'promotion_date' => '2013-06-25', 'graduation_announce_date' => '2019-03-30', 'graduation_announce_event' => 'High Tension Handshake Festival', 'graduation_date' => '2019-07-27', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Della Delila', 'nickname' => 'Della', 'birth_place' => 'Jakarta', 'birth_date' => '1998-11-15', 'gen' => '2', 'join_date' => '2012-11-03', 'status' => 'Lulus', 'promotion_date' => '2013-06-25', 'graduation_announce_date' => '2019-01-12', 'graduation_announce_event' => 'Sekarang Sedang Jatuh Cinta', 'graduation_date' => '2019-03-31', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Dellia Erdita', 'nickname' => 'Dellia', 'birth_place' => 'Banten', 'birth_date' => '1996-12-19', 'gen' => '2', 'join_date' => '2012-11-03', 'status' => 'Lulus', 'graduation_date' => '2013-11-30', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Dena Siti Rohyati', 'nickname' => 'Dena', 'birth_place' => 'Depok', 'birth_date' => '1997-03-15', 'gen' => '2', 'join_date' => '2012-11-03', 'status' => 'Lulus', 'graduation_date' => '2018-04-05', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Dwi Putri Bonita', 'nickname' => 'Uty', 'birth_place' => 'Palembang', 'birth_date' => '1997-11-17', 'gen' => '2', 'join_date' => '2012-11-03', 'status' => 'Lulus', 'promotion_date' => '2013-06-25', 'graduation_announce_date' => '2018-07-21', 'graduation_announce_event' => 'Sekarang Sedang Jatuh Cinta', 'graduation_date' => '2018-09-30', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Fakhriyani Shafariyanti', 'nickname' => 'Shafa', 'birth_place' => 'Depok', 'birth_date' => '1995-07-14', 'gen' => '2', 'join_date' => '2012-11-03', 'status' => 'Lulus', 'graduation_announce_date' => '2018-01-20', 'graduation_announce_event' => 'Team KIII B•E•L•I•E•V•E Show', 'graduation_date' => '2018-03-25', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Intar Putri Kariina', 'nickname' => 'Kariin', 'birth_place' => 'Bandung', 'birth_date' => '1997-10-23', 'gen' => '2', 'join_date' => '2012-11-03', 'status' => 'Lulus', 'promotion_date' => '2013-06-25', 'graduation_date' => '2013-09-09', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Jennifer Hanna', 'nickname' => 'Hanna', 'birth_place' => 'Banjarmasin', 'birth_date' => '1998-01-26', 'gen' => '2', 'join_date' => '2012-11-03', 'status' => 'Lulus', 'promotion_date' => '2013-06-25', 'graduation_announce_date' => '2016-09-07', 'graduation_announce_event' => 'Bel Terakhir Berbunyi', 'graduation_date' => '2016-09-27', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Jennifer Rachel Natasya', 'nickname' => 'Rachel', 'birth_place' => 'Jakarta', 'birth_date' => '1999-04-10', 'gen' => '2', 'join_date' => '2012-11-03', 'status' => 'Lulus', 'graduation_announce_date' => '2019-08-18', 'graduation_announce_event' => 'JKT48 Sousenkyo 2019 Announcement', 'graduation_date' => '2020-01-05', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Lidya Maulida Djuhandar', 'nickname' => 'Lidya', 'birth_place' => 'Jakarta', 'birth_date' => '1996-08-17', 'gen' => '2', 'join_date' => '2012-11-03', 'status' => 'Lulus', 'promotion_date' => '2013-06-25', 'graduation_announce_date' => '2018-08-17', 'graduation_announce_event' => 'Gadis Gadis Remaja', 'graduation_date' => '2018-10-27', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Nadhifa Karimah', 'nickname' => 'Nadhifa', 'birth_place' => '', 'birth_date' => '1995-11-24', 'gen' => '2', 'join_date' => '2012-11-03', 'status' => 'Lulus', 'graduation_date' => '2013-11-30', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Nadila Cindi Wantari', 'nickname' => 'Nadila', 'birth_place' => 'Kota Bogor', 'birth_date' => '1998-09-23', 'gen' => '2', 'join_date' => '2012-11-03', 'status' => 'Lulus', 'promotion_date' => '2013-06-25', 'graduation_announce_date' => '2020-11-08', 'graduation_announce_event' => 'Fajar Sang Idola', 'graduation_date' => '2021-02-07', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Natalia', 'nickname' => 'Natalia', 'birth_place' => 'Jakarta', 'birth_date' => '1996-12-28', 'gen' => '2', 'join_date' => '2012-11-03', 'status' => 'Lulus', 'promotion_date' => '2013-06-25', 'graduation_announce_date' => '2019-03-22', 'graduation_announce_event' => 'Saka Agari', 'graduation_date' => '2019-07-20', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Noella Sisterina', 'nickname' => 'Noella', 'birth_place' => 'Surabaya', 'birth_date' => '1997-11-16', 'gen' => '2', 'join_date' => '2012-11-03', 'status' => 'Lulus', 'promotion_date' => '2013-06-25', 'graduation_date' => '2015-02-27', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Novinta Dhini', 'nickname' => 'Novinta', 'birth_place' => 'Denpasar', 'birth_date' => '1995-11-26', 'gen' => '2', 'join_date' => '2012-11-03', 'status' => 'Lulus', 'graduation_date' => '2015-08-17', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Nurhalima Oktavianti', 'nickname' => 'Halimah', 'birth_place' => '', 'birth_date' => '1996-10-18', 'gen' => '2', 'join_date' => '2012-11-03', 'status' => 'Lulus', 'graduation_date' => '2013-01-10', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Octi Sevpin', 'nickname' => 'Octi', 'birth_place' => 'Jakarta', 'birth_date' => '1997-10-07', 'gen' => '2', 'join_date' => '2012-11-03', 'status' => 'Lulus', 'promotion_date' => '2013-06-25', 'graduation_date' => '2014-01-23', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Olivia Robberecht', 'nickname' => 'Olivia', 'birth_place' => 'Belanda', 'birth_date' => '1997-05-21', 'gen' => '2', 'join_date' => '2012-11-03', 'status' => 'Lulus', 'graduation_date' => '2013-04-12', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Priscillia Sari Dewi', 'nickname' => 'Sisil', 'birth_place' => 'Palembang', 'birth_date' => '1999-04-05', 'gen' => '2', 'join_date' => '2012-11-03', 'status' => 'Lulus', 'graduation_date' => '2018-07-31', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Ratu Vienny Fitrilya', 'nickname' => 'Viny', 'birth_place' => 'Pandeglang', 'birth_date' => '1996-02-23', 'gen' => '2', 'join_date' => '2012-11-03', 'status' => 'Lulus', 'promotion_date' => '2013-06-25', 'graduation_announce_date' => '2019-07-13', 'graduation_announce_event' => 'JKT48 Circus Surabaya - City of Tomorrow Surabaya', 'graduation_date' => '2020-02-23', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Riskha Fairunissa', 'nickname' => 'Ikha', 'birth_place' => 'Jakarta', 'birth_date' => '1996-03-22', 'gen' => '2', 'join_date' => '2012-11-03', 'status' => 'Lulus', 'promotion_date' => '2013-06-25', 'graduation_announce_date' => '2018-08-17', 'graduation_announce_event' => 'Gadis Gadis Remaja', 'graduation_date' => '2018-12-29', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Rona Anggreani', 'nickname' => 'Rona', 'birth_place' => 'Pasuruan', 'birth_date' => '1995-03-19', 'gen' => '2', 'join_date' => '2012-11-03', 'status' => 'Lulus', 'promotion_date' => '2013-06-25', 'graduation_announce_date' => '2020-11-08', 'graduation_announce_event' => 'Fajar Sang Idola', 'graduation_date' => '2021-02-13', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Saktia Oktapyani', 'nickname' => 'Saktia', 'birth_place' => 'Jakarta', 'birth_date' => '1995-10-01', 'gen' => '2', 'join_date' => '2012-11-03', 'status' => 'Lulus', 'graduation_announce_date' => '2019-01-12', 'graduation_announce_event' => 'Sekarang Sedang Jatuh Cinta', 'graduation_date' => '2019-03-31', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Shinta Naomi', 'nickname' => 'Naomi', 'birth_place' => 'Jakarta', 'birth_date' => '1994-06-04', 'gen' => '2', 'join_date' => '2012-11-03', 'status' => 'Lulus', 'promotion_date' => '2013-06-25', 'graduation_announce_date' => '2018-08-17', 'graduation_announce_event' => 'Gadis Gadis Remaja', 'graduation_date' => '2018-12-29', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Sinka Juliani', 'nickname' => 'Sinka', 'birth_place' => 'Jakarta', 'birth_date' => '1996-07-04', 'gen' => '2', 'join_date' => '2012-11-03', 'status' => 'Lulus', 'promotion_date' => '2013-06-25', 'graduation_announce_date' => '2019-07-11', 'graduation_announce_event' => 'Fajar Sang Idola', 'graduation_date' => '2019-10-05', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Thalia', 'nickname' => 'Tata', 'birth_place' => 'Jakarta', 'birth_date' => '1996-12-22', 'gen' => '2', 'join_date' => '2012-11-03', 'status' => 'Lulus', 'promotion_date' => '2013-06-25', 'graduation_date' => '2015-08-26', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Thalia Ivanka Elizabeth', 'nickname' => 'Vanka', 'birth_place' => 'Jakarta', 'birth_date' => '1999-06-29', 'gen' => '2', 'join_date' => '2012-11-03', 'status' => 'Lulus', 'graduation_announce_date' => '2019-08-18', 'graduation_announce_event' => 'JKT48 Sousenkyo 2019 Announcement', 'graduation_date' => '2019-12-06', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Viviyona Apriani', 'nickname' => 'Yona', 'birth_place' => 'Jakarta', 'birth_date' => '1994-04-13', 'gen' => '2', 'join_date' => '2012-11-03', 'status' => 'Lulus', 'promotion_date' => '2013-06-25', 'graduation_announce_date' => '2019-08-10', 'graduation_announce_event' => 'Saka Agari', 'graduation_date' => '2019-12-21', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],

            // Generasi 3
            ['name' => 'Alycia Ferryana', 'nickname' => 'Cia', 'birth_place' => 'Jakarta', 'birth_date' => '1998-05-22', 'gen' => '3', 'join_date' => '2014-03-15', 'status' => 'Lulus', 'graduation_date' => '2016-02-01', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Amanda Dwi Arista', 'nickname' => 'Manda', 'birth_place' => 'Jakarta', 'birth_date' => '1997-03-24', 'gen' => '3', 'join_date' => '2014-03-15', 'status' => 'Lulus', 'graduation_date' => '2018-05-23', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Andela Yuwono', 'nickname' => 'Andela', 'birth_place' => 'Semarang', 'birth_date' => '1997-04-25', 'gen' => '3', 'join_date' => '2014-03-15', 'status' => 'Lulus', 'graduation_date' => '2015-09-04', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Anggie Putri Kurniasari', 'nickname' => 'Anggie', 'birth_place' => 'Surabaya', 'birth_date' => '1996-03-13', 'gen' => '3', 'join_date' => '2014-03-15', 'status' => 'Lulus', 'graduation_date' => '2015-03-23', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Aninditha Rahma Cahyadi', 'nickname' => 'Anin', 'birth_place' => 'Palembang', 'birth_date' => '1999-01-05', 'gen' => '3', 'join_date' => '2014-03-15', 'status' => 'Lulus', 'graduation_announce_date' => '2021-12-23', 'graduation_announce_event' => 'Aturan Anti Cinta', 'graduation_date' => '2022-05-22', 'restructure_status' => 'Lulus Setelah Restrukturisasi'],
            ['name' => 'Ayu Safira Oktaviani', 'nickname' => 'Okta', 'birth_place' => 'Jakarta', 'birth_date' => '1999-10-01', 'gen' => '3', 'join_date' => '2014-03-15', 'status' => 'Lulus', 'graduation_date' => '2019-04-23', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Chikita Ravenska Mamesah', 'nickname' => 'Chikita', 'birth_place' => 'Bandung', 'birth_date' => '1996-03-18', 'gen' => '3', 'join_date' => '2014-03-15', 'status' => 'Lulus', 'graduation_announce_date' => '2016-03-15', 'graduation_announce_event' => 'Sambil Menggandeng Erat Tanganku', 'graduation_date' => '2016-05-29', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Elaine Hartanto', 'nickname' => 'Elaine', 'birth_place' => 'Jakarta', 'birth_date' => '1996-04-03', 'gen' => '3', 'join_date' => '2014-03-15', 'status' => 'Lulus', 'graduation_announce_date' => '2016-03-12', 'graduation_announce_event' => 'Dewi Theater', 'graduation_date' => '2016-04-03', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Farina Yogi Devani', 'nickname' => 'Farina', 'birth_place' => 'Jakarta', 'birth_date' => '1999-05-11', 'gen' => '3', 'join_date' => '2014-03-15', 'status' => 'Lulus', 'graduation_date' => '2016-02-01', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Feni Fitriyanti', 'nickname' => 'Feni', 'birth_place' => 'Cianjur', 'birth_date' => '1999-01-16', 'gen' => '3', 'join_date' => '2014-03-15', 'status' => 'Aktif', 'restructure_status' => 'Masih Aktif (Masuk Sebelum Restrukturisasi)'],
            ['name' => 'Fransisca Saraswati Puspa Dewi', 'nickname' => 'Sisca', 'birth_place' => 'Jakarta', 'birth_date' => '2000-02-24', 'gen' => '3', 'join_date' => '2014-03-15', 'status' => 'Lulus', 'graduation_announce_date' => '2023-03-15', 'graduation_announce_event' => 'Aturan Anti Cinta', 'graduation_date' => '2023-09-02', 'restructure_status' => 'Lulus Setelah Restrukturisasi'],
            ['name' => 'Indah Permata Sari', 'nickname' => 'Indah', 'birth_place' => 'Bogor', 'birth_date' => '1998-01-19', 'gen' => '3', 'join_date' => '2014-03-15', 'status' => 'Lulus', 'graduation_date' => '2016-02-01', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Kezia Putri Andinta', 'nickname' => 'Kei', 'birth_place' => 'Jakarta', 'birth_date' => '2001-01-28', 'gen' => '3', 'join_date' => '2014-03-15', 'status' => 'Lulus', 'graduation_date' => '2014-11-22', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Maria Genoveva Natalia Desy Purnamasari Gunawan', 'nickname' => 'Desy', 'birth_place' => 'Yogyakarta', 'birth_date' => '1996-12-25', 'gen' => '3', 'join_date' => '2014-03-15', 'status' => 'Lulus', 'graduation_announce_date' => '2020-10-25', 'graduation_announce_event' => 'Saka Agari', 'graduation_date' => '2020-12-26', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Martha Graciela', 'nickname' => 'Grace', 'birth_place' => 'Pekanbaru', 'birth_date' => '1999-03-05', 'gen' => '3', 'join_date' => '2014-03-15', 'status' => 'Lulus', 'graduation_announce_date' => '2016-03-15', 'graduation_announce_event' => 'Sambil Menggandeng Erat Tanganku', 'graduation_date' => '2016-04-22', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Michelle Christo Kusnadi', 'nickname' => 'Michelle', 'birth_place' => 'Jakarta', 'birth_date' => '1999-10-28', 'gen' => '3', 'join_date' => '2014-03-15', 'status' => 'Lulus', 'graduation_announce_date' => '2019-08-18', 'graduation_announce_event' => 'JKT48 Sousenkyo 2019 Announcement', 'graduation_date' => '2020-01-18', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Milenia Christien Glory Goenawan', 'nickname' => 'Milen', 'birth_place' => 'Pontianak', 'birth_date' => '2000-03-12', 'gen' => '3', 'join_date' => '2014-03-15', 'status' => 'Lulus', 'graduation_date' => '2014-11-22', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Nadhifa Salsabila', 'nickname' => 'Nadse', 'birth_place' => 'Padang', 'birth_date' => '1999-03-07', 'gen' => '3', 'join_date' => '2014-03-15', 'status' => 'Lulus', 'graduation_date' => '2017-02-16', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Ni Made Ayu Vania Aurellia', 'nickname' => 'Aurel', 'birth_place' => 'Kota Tangerang', 'birth_date' => '1999-08-08', 'gen' => '3', 'join_date' => '2014-03-15', 'status' => 'Lulus', 'graduation_date' => '2020-12-13', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Nina Hamidah', 'nickname' => 'Nina', 'birth_place' => 'Jakarta', 'birth_date' => '2000-03-02', 'gen' => '3', 'join_date' => '2014-03-15', 'status' => 'Lulus', 'graduation_date' => '2016-02-01', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Pipit Ananda', 'nickname' => 'Pipit', 'birth_place' => '', 'birth_date' => '1998-02-06', 'gen' => '3', 'join_date' => '2014-03-15', 'status' => 'Lulus', 'graduation_date' => '2014-03-24', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Putri Farin Kartika', 'nickname' => 'Farin', 'birth_place' => 'Jakarta', 'birth_date' => '1996-09-05', 'gen' => '3', 'join_date' => '2014-03-15', 'status' => 'Lulus', 'graduation_date' => '2016-02-01', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Rizka Khalila', 'nickname' => 'Yukka', 'birth_place' => 'Bogor', 'birth_date' => '1999-02-19', 'gen' => '3', 'join_date' => '2014-03-15', 'status' => 'Lulus', 'graduation_date' => '2015-03-23', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Shaffa Nabila', 'nickname' => 'Afa', 'birth_place' => '', 'birth_date' => '1998-03-06', 'gen' => '3', 'join_date' => '2014-03-15', 'status' => 'Lulus', 'graduation_date' => '2014-08-11', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Shani Indira Natio', 'nickname' => 'Shani', 'birth_place' => 'Kebumen', 'birth_date' => '1998-10-05', 'gen' => '3', 'join_date' => '2014-03-15', 'status' => 'Lulus', 'graduation_announce_date' => '2023-07-02', 'graduation_announce_event' => 'JKT48 Summer Festival 2023', 'graduation_date' => '2024-05-11', 'restructure_status' => 'Lulus Setelah Restrukturisasi'],
            ['name' => 'Shania Gracia', 'nickname' => 'Gracia', 'birth_place' => 'Jakarta', 'birth_date' => '1999-08-31', 'gen' => '3', 'join_date' => '2014-03-15', 'status' => 'Aktif', 'restructure_status' => 'Masih Aktif (Masuk Sebelum Restrukturisasi)'],
            ['name' => 'Sofia Meifaliani', 'nickname' => 'Sofia', 'birth_place' => 'Bekasi', 'birth_date' => '1998-04-23', 'gen' => '3', 'join_date' => '2014-03-15', 'status' => 'Lulus', 'graduation_announce_date' => '2016-03-12', 'graduation_announce_event' => 'Dewi Theater', 'graduation_date' => '2016-04-27', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Stephanie Pricilla Indarto Putri', 'nickname' => 'Stefi', 'birth_place' => 'Jakarta', 'birth_date' => '2000-11-19', 'gen' => '3', 'join_date' => '2014-03-15', 'status' => 'Lulus', 'graduation_announce_date' => '2019-08-18', 'graduation_announce_event' => 'JKT48 Sousenkyo 2019 Announcement', 'graduation_date' => '2019-09-28', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Syahfira Angela Nurhaliza', 'nickname' => 'Angel', 'birth_place' => 'Jakarta', 'birth_date' => '2000-12-20', 'gen' => '3', 'join_date' => '2014-03-15', 'status' => 'Lulus', 'graduation_announce_date' => '2019-08-18', 'graduation_announce_event' => 'JKT48 Sousenkyo 2019 Announcement', 'graduation_date' => '2019-12-13', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Triarona Kusuma', 'nickname' => 'Tya', 'birth_place' => 'Jakarta', 'birth_date' => '1996-12-06', 'gen' => '3', 'join_date' => '2014-03-15', 'status' => 'Lulus', 'graduation_date' => '2016-02-01', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Yansen Indiani', 'nickname' => 'Cesen', 'birth_place' => 'Jakarta', 'birth_date' => '1999-06-15', 'gen' => '3', 'join_date' => '2014-03-15', 'status' => 'Lulus', 'graduation_date' => '2017-03-02', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Zebi Magnolia Fawwaz', 'nickname' => 'Zebi', 'birth_place' => 'Jakarta', 'birth_date' => '2000-11-10', 'gen' => '3', 'join_date' => '2014-03-15', 'status' => 'Lulus', 'graduation_date' => '2014-12-26', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],

            // Generasi 4
            ['name' => 'Adriani Elisabeth', 'nickname' => 'Lisa', 'birth_place' => 'Purbalingga', 'birth_date' => '2000-05-10', 'gen' => '4', 'join_date' => '2015-05-16', 'status' => 'Lulus', 'graduation_date' => '2021-03-14', 'restructure_status' => 'Lulus Terkena Restrukturisasi'],
            ['name' => 'Christi', 'nickname' => 'Christi', 'birth_place' => 'Jakarta', 'birth_date' => '1999-11-14', 'gen' => '4', 'join_date' => '2015-05-16', 'status' => 'Lulus', 'graduation_announce_date' => '2017-10-10', 'graduation_announce_event' => 'Matahari Milikku', 'graduation_date' => '2017-10-21', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Cindy Hapsari Maharani Pujiantoro Putri', 'nickname' => 'Cindy', 'birth_place' => 'Banyumas', 'birth_date' => '1998-09-13', 'gen' => '4', 'join_date' => '2015-05-16', 'status' => 'Lulus', 'graduation_announce_date' => '2022-03-13', 'graduation_announce_event' => 'Aturan Anti Cinta', 'graduation_date' => '2022-07-17', 'restructure_status' => 'Lulus Setelah Restrukturisasi'],
            ['name' => 'Fidly Immanda Azzahra', 'nickname' => 'Fia', 'birth_place' => 'Karawang', 'birth_date' => '2001-03-19', 'gen' => '4', 'join_date' => '2015-05-16', 'status' => 'Lulus', 'graduation_date' => '2021-03-13', 'restructure_status' => 'Lulus Terkena Restrukturisasi'],
            ['name' => 'Jessica Berliana Ekawardani', 'nickname' => 'Jessica', 'birth_place' => 'Karawang', 'birth_date' => '1999-07-04', 'gen' => '4', 'join_date' => '2015-05-16', 'status' => 'Lulus', 'graduation_date' => '2015-10-31', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Jinan Safa Safira', 'nickname' => 'Jinan', 'birth_place' => 'Jakarta', 'birth_date' => '1999-06-08', 'gen' => '4', 'join_date' => '2015-05-16', 'status' => 'Lulus', 'graduation_announce_date' => '2022-12-23', 'graduation_announce_event' => 'BANZAI JKT48', 'graduation_date' => '2023-03-18', 'restructure_status' => 'Lulus Setelah Restrukturisasi'],
            ['name' => 'Made Devi Ranita Ningtara', 'nickname' => 'Devi', 'birth_place' => 'Denpasar', 'birth_date' => '2000-11-18', 'gen' => '4', 'join_date' => '2015-05-16', 'status' => 'Lulus', 'graduation_announce_date' => '2018-08-11', 'graduation_announce_event' => 'Gadis Gadis Remaja', 'graduation_date' => '2018-12-27', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Mega Suryani', 'nickname' => 'Mega', 'birth_place' => 'Bandung', 'birth_date' => '2002-07-09', 'gen' => '4', 'join_date' => '2015-05-16', 'status' => 'Lulus', 'graduation_date' => '2015-10-31', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Melati Putri Rahel Sesilia', 'nickname' => 'Melati', 'birth_place' => 'Jakarta', 'birth_date' => '2000-01-01', 'gen' => '4', 'join_date' => '2015-05-16', 'status' => 'Lulus', 'graduation_announce_date' => '2020-02-27', 'graduation_announce_event' => 'Fajar Sang Idola', 'graduation_date' => '2020-10-24', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Sri Lintang', 'nickname' => 'Lintang', 'birth_place' => 'Jakarta', 'birth_date' => '2000-11-05', 'gen' => '4', 'join_date' => '2015-05-16', 'status' => 'Lulus', 'graduation_date' => '2017-12-07', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Tan Zhi Hui Celine', 'nickname' => 'Celine', 'birth_place' => 'Johor Bahru', 'birth_date' => '2001-08-21', 'gen' => '4', 'join_date' => '2015-05-16', 'status' => 'Lulus', 'graduation_announce_date' => '2022-04-27', 'graduation_announce_event' => 'Courtroom48', 'graduation_date' => '2022-08-13', 'restructure_status' => 'Lulus Setelah Restrukturisasi'],
            ['name' => 'Zahra Yuriva Dermawan', 'nickname' => 'Yuri', 'birth_place' => 'Bandung', 'birth_date' => '2000-07-10', 'gen' => '4', 'join_date' => '2015-05-16', 'status' => 'Lulus', 'graduation_date' => '2018-02-10', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],

            // Generasi 5
            ['name' => 'Adhisty Zara', 'nickname' => 'Zara', 'birth_place' => 'Bandung', 'birth_date' => '2003-06-21', 'gen' => '5', 'join_date' => '2016-05-28', 'status' => 'Lulus', 'graduation_announce_date' => '2019-08-13', 'graduation_announce_event' => 'Sambil Menggandeng Erat Tanganku', 'graduation_date' => '2019-12-04', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Anggita Destiana Dewi', 'nickname' => 'Anggi', 'birth_place' => 'Bandung', 'birth_date' => '2001-12-26', 'gen' => '5', 'join_date' => '2016-05-28', 'status' => 'Lulus', 'graduation_date' => '2016-06-27', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Chintya Hanindhitakirana Wirawan', 'nickname' => 'Chintya', 'birth_place' => 'Jakarta', 'birth_date' => '1999-12-29', 'gen' => '5', 'join_date' => '2016-05-28', 'status' => 'Lulus', 'graduation_date' => '2017-02-16', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Citra Ayu Pranajaya Wibrado', 'nickname' => 'Citra', 'birth_place' => 'Jakarta', 'birth_date' => '1999-08-25', 'gen' => '5', 'join_date' => '2016-05-28', 'status' => 'Lulus', 'graduation_date' => '2018-06-30', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Diani Amalia Ramadhani', 'nickname' => 'Diani', 'birth_place' => 'Pekalongan', 'birth_date' => '1999-01-05', 'gen' => '5', 'join_date' => '2016-05-28', 'status' => 'Lulus', 'graduation_date' => '2021-03-14', 'restructure_status' => 'Lulus Terkena Restrukturisasi'],
            ['name' => 'Elizabeth Gloria Setiawan', 'nickname' => 'Ori', 'birth_place' => 'Tangerang', 'birth_date' => '2002-02-14', 'gen' => '5', 'join_date' => '2016-05-28', 'status' => 'Lulus', 'graduation_date' => '2018-04-13', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Eve Antoinette Ichwan', 'nickname' => 'Eve', 'birth_place' => 'Jakarta', 'birth_date' => '2003-10-17', 'gen' => '5', 'join_date' => '2016-05-28', 'status' => 'Lulus', 'graduation_announce_date' => '2021-12-26', 'graduation_announce_event' => 'Tunas di Balik Seragam', 'graduation_date' => '2022-02-13', 'restructure_status' => 'Lulus Setelah Restrukturisasi'],
            ['name' => 'Gabryela Marcelina', 'nickname' => 'Aby', 'birth_place' => 'Kota Bogor', 'birth_date' => '2001-09-06', 'gen' => '5', 'join_date' => '2016-05-28', 'status' => 'Lulus', 'graduation_date' => '2020-11-16', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Hasyakyla Utami Kusumawardhani', 'nickname' => 'Kyla', 'birth_place' => 'Bandung', 'birth_date' => '2002-05-20', 'gen' => '5', 'join_date' => '2016-05-28', 'status' => 'Lulus', 'graduation_announce_date' => '2019-08-18', 'graduation_announce_event' => 'JKT48 Sousenkyo 2019 Announcement', 'graduation_date' => '2019-11-10', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Helma Sonya', 'nickname' => 'Helma', 'birth_place' => 'Garut', 'birth_date' => '1999-03-20', 'gen' => '5', 'join_date' => '2016-05-28', 'status' => 'Lulus', 'graduation_date' => '2016-09-09', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Nurhayati', 'nickname' => 'Aya', 'birth_place' => 'Palembang', 'birth_date' => '1997-10-18', 'gen' => '5', 'join_date' => '2016-05-28', 'status' => 'Lulus', 'graduation_date' => '2021-03-13', 'restructure_status' => 'Lulus Terkena Restrukturisasi'],
            ['name' => 'Puti Nadhira Azalia', 'nickname' => 'Puti', 'birth_place' => 'Jakarta', 'birth_date' => '2000-06-07', 'gen' => '5', 'join_date' => '2016-05-28', 'status' => 'Lulus', 'graduation_announce_date' => '2020-02-26', 'graduation_announce_event' => 'Saka Agari', 'graduation_date' => '2020-05-18', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Regina Angelina', 'nickname' => 'Regina', 'birth_place' => 'Jakarta', 'birth_date' => '2001-05-09', 'gen' => '5', 'join_date' => '2016-05-28', 'status' => 'Lulus', 'graduation_date' => '2017-11-01', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Rissanda Putri Tuarissa', 'nickname' => 'Sanda', 'birth_place' => 'Jakarta', 'birth_date' => '1999-08-04', 'gen' => '5', 'join_date' => '2016-05-28', 'status' => 'Lulus', 'graduation_date' => '2016-09-09', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Ruth Damayanti Sitanggang', 'nickname' => 'Ruth', 'birth_place' => 'Tangerang', 'birth_date' => '1998-11-12', 'gen' => '5', 'join_date' => '2016-05-28', 'status' => 'Lulus', 'graduation_date' => '2018-06-30', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Sania Julia Montolalu', 'nickname' => 'Julie', 'birth_place' => 'Jakarta', 'birth_date' => '2001-07-18', 'gen' => '5', 'join_date' => '2016-05-28', 'status' => 'Lulus', 'graduation_date' => '2021-03-14', 'restructure_status' => 'Lulus Terkena Restrukturisasi'],
            ['name' => 'Violeta Burhan', 'nickname' => 'Violet', 'birth_place' => 'Jakarta', 'birth_date' => '2002-01-04', 'gen' => '5', 'join_date' => '2016-05-28', 'status' => 'Lulus', 'graduation_date' => '2018-07-03', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],

            // Generasi 6
            ['name' => 'Amanda Priscella Solichin', 'nickname' => 'Ella', 'birth_place' => '', 'birth_date' => '2003-08-20', 'gen' => '6', 'join_date' => '2018-04-08', 'status' => 'Lulus', 'graduation_date' => '2018-12-12', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Anastasya Narwastu Tety Handuran', 'nickname' => 'Tasya', 'birth_place' => 'Jakarta', 'birth_date' => '2000-06-16', 'gen' => '6', 'join_date' => '2018-04-08', 'status' => 'Lulus', 'graduation_date' => '2021-03-13', 'restructure_status' => 'Lulus Terkena Restrukturisasi'],
            ['name' => 'Ariella Calista Ichwan', 'nickname' => 'Ariel', 'birth_place' => 'Jakarta', 'birth_date' => '2000-05-12', 'gen' => '6', 'join_date' => '2018-04-08', 'status' => 'Lulus', 'graduation_announce_date' => '2021-12-26', 'graduation_announce_event' => 'Tunas di Balik Seragam', 'graduation_date' => '2022-02-13', 'restructure_status' => 'Lulus Setelah Restrukturisasi'],
            ['name' => 'Denise Caroline', 'nickname' => 'Denise', 'birth_place' => 'Jakarta', 'birth_date' => '2001-12-23', 'gen' => '6', 'join_date' => '2018-04-08', 'status' => 'Lulus', 'graduation_date' => '2018-08-21', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Erika Ebisawa Kuswan', 'nickname' => 'Erika', 'birth_place' => 'Bekasi', 'birth_date' => '1999-10-15', 'gen' => '6', 'join_date' => '2018-04-08', 'status' => 'Lulus', 'graduation_date' => '2019-02-09', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Erika Sintia', 'nickname' => 'Sintia', 'birth_place' => '', 'birth_date' => '2000-04-16', 'gen' => '6', 'join_date' => '2018-04-08', 'status' => 'Lulus', 'graduation_date' => '2019-01-24', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Gita Sekar Andarini', 'nickname' => 'Gita', 'birth_place' => 'Jakarta', 'birth_date' => '2001-06-30', 'gen' => '6', 'join_date' => '2018-04-08', 'status' => 'Aktif', 'restructure_status' => 'Masih Aktif (Masuk Sebelum Restrukturisasi)'],
            ['name' => 'Graciella Ruth Wiranto', 'nickname' => 'Ciel', 'birth_place' => 'Bogor', 'birth_date' => '2004-03-05', 'gen' => '6', 'join_date' => '2018-04-08', 'status' => 'Lulus', 'graduation_date' => '2019-06-15', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Jihan Miftahul Jannah', 'nickname' => 'Jee', 'birth_place' => 'Jakarta', 'birth_date' => '2001-01-13', 'gen' => '6', 'join_date' => '2018-04-08', 'status' => 'Lulus', 'graduation_date' => '2018-04-21', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Kandiya Rafa Maulidita', 'nickname' => 'Indy', 'birth_place' => 'Jakarta', 'birth_date' => '2003-05-14', 'gen' => '6', 'join_date' => '2018-04-08', 'status' => 'Lulus', 'graduation_date' => '2021-03-13', 'restructure_status' => 'Lulus Terkena Restrukturisasi'],
            ['name' => 'Putri Cahyaning Anggraini', 'nickname' => 'Riri', 'birth_place' => 'Kota Kediri', 'birth_date' => '2001-12-25', 'gen' => '6', 'join_date' => '2018-04-08', 'status' => 'Lulus', 'graduation_date' => '2018-11-01', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Rinanda Syahputri', 'nickname' => 'Nanda', 'birth_place' => 'Jakarta', 'birth_date' => '2003-09-13', 'gen' => '6', 'join_date' => '2018-04-08', 'status' => 'Lulus', 'graduation_date' => '2021-03-13', 'restructure_status' => 'Lulus Terkena Restrukturisasi'],
            ['name' => 'Riska Amelia Putri', 'nickname' => 'Amel', 'birth_place' => 'Banyumas', 'birth_date' => '2000-03-18', 'gen' => '6', 'join_date' => '2018-04-08', 'status' => 'Lulus', 'graduation_date' => '2021-03-14', 'restructure_status' => 'Lulus Terkena Restrukturisasi'],
            ['name' => 'Shalza Grasita', 'nickname' => 'Shalza', 'birth_place' => 'Jakarta', 'birth_date' => '2004-10-07', 'gen' => '6', 'join_date' => '2018-04-08', 'status' => 'Lulus', 'graduation_date' => '2020-09-22', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],

            // Generasi 7
            ['name' => 'Aiko Harumi Nangin', 'nickname' => 'Aiko', 'birth_place' => 'Kota Bekasi', 'birth_date' => '2002-03-23', 'gen' => '7', 'join_date' => '2018-09-29', 'status' => 'Lulus', 'graduation_date' => '2020-07-29', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Angelina Christy', 'nickname' => 'Christy', 'birth_place' => 'Jakarta', 'birth_date' => '2005-12-05', 'gen' => '7', 'join_date' => '2018-09-29', 'status' => 'Aktif', 'restructure_status' => 'Masih Aktif (Masuk Sebelum Restrukturisasi)'],
            ['name' => 'Aurel Mayori', 'nickname' => 'Yori', 'birth_place' => 'Tangerang', 'birth_date' => '2006-05-14', 'gen' => '7', 'join_date' => '2018-09-29', 'status' => 'Lulus', 'graduation_date' => '2021-03-12', 'restructure_status' => 'Lulus Terkena Restrukturisasi'],
            ['name' => 'Azizi Asadel', 'nickname' => 'Zee', 'birth_place' => 'Tangerang', 'birth_date' => '2004-05-16', 'gen' => '7', 'join_date' => '2018-09-29', 'status' => 'Lulus', 'graduation_announce_date' => '2024-04-07', 'graduation_announce_event' => 'Event \"ANAK KING\"', 'graduation_date' => '2024-08-25', 'restructure_status' => 'Lulus Setelah Restrukturisasi'],
            ['name' => 'Calista Lea Jaya', 'nickname' => 'Lea', 'birth_place' => '', 'birth_date' => '2002-07-15', 'gen' => '7', 'join_date' => '2018-09-29', 'status' => 'Lulus', 'graduation_date' => '2019-01-24', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Dhea Angelia', 'nickname' => 'Dey', 'birth_place' => 'Jakarta', 'birth_date' => '2001-08-18', 'gen' => '7', 'join_date' => '2018-09-29', 'status' => 'Lulus', 'graduation_announce_date' => '2022-11-26', 'graduation_announce_event' => 'IDOL ROLL - Episode 2', 'graduation_date' => '2023-02-23', 'restructure_status' => 'Lulus Setelah Restrukturisasi'],
            ['name' => 'Febi Komaril', 'nickname' => 'Febi', 'birth_place' => 'Jakarta', 'birth_date' => '2000-02-03', 'gen' => '7', 'join_date' => '2018-09-29', 'status' => 'Lulus', 'graduation_date' => '2021-03-11', 'restructure_status' => 'Lulus Terkena Restrukturisasi'],
            ['name' => 'Febrina Diponegoro', 'nickname' => 'Bri', 'birth_place' => 'Bekasi', 'birth_date' => '2002-02-17', 'gen' => '7', 'join_date' => '2018-09-29', 'status' => 'Lulus', 'graduation_date' => '2021-03-11', 'restructure_status' => 'Lulus Terkena Restrukturisasi'],
            ['name' => 'Febriola Sinambela', 'nickname' => 'Olla', 'birth_place' => 'Jakarta', 'birth_date' => '2005-02-26', 'gen' => '7', 'join_date' => '2018-09-29', 'status' => 'Aktif', 'restructure_status' => 'Masih Aktif (Masuk Sebelum Restrukturisasi)'],
            ['name' => 'Freya Jayawardana', 'nickname' => 'Freya', 'birth_place' => 'Tangerang', 'birth_date' => '2006-02-13', 'gen' => '7', 'join_date' => '2018-09-29', 'status' => 'Aktif', 'restructure_status' => 'Masih Aktif (Masuk Sebelum Restrukturisasi)'],
            ['name' => 'Gabriel Angelina', 'nickname' => 'Brielle', 'birth_place' => 'Batam', 'birth_date' => '2004-07-17', 'gen' => '7', 'join_date' => '2018-09-29', 'status' => 'Lulus', 'graduation_date' => '2021-03-14', 'restructure_status' => 'Lulus Terkena Restrukturisasi'],
            ['name' => 'Helisma Putri', 'nickname' => 'Eli', 'birth_place' => 'Bandung Barat', 'birth_date' => '2000-06-15', 'gen' => '7', 'join_date' => '2018-09-29', 'status' => 'Aktif', 'restructure_status' => 'Masih Aktif (Masuk Sebelum Restrukturisasi)'],
            ['name' => 'Jessica Chandra', 'nickname' => 'Jessi', 'birth_place' => 'Jakarta', 'birth_date' => '2005-09-23', 'gen' => '7', 'join_date' => '2018-09-29', 'status' => 'Aktif', 'restructure_status' => 'Masih Aktif (Masuk Sebelum Restrukturisasi)'],
            ['name' => 'Jesslyn Callista', 'nickname' => 'Jesslyn', 'birth_place' => 'Tangerang Selatan', 'birth_date' => '2000-04-20', 'gen' => '7', 'join_date' => '2018-09-29', 'status' => 'Lulus', 'graduation_announce_date' => '2023-06-03', 'graduation_announce_event' => 'Cara Meminum Ramune', 'graduation_date' => '2023-07-29', 'restructure_status' => 'Lulus Setelah Restrukturisasi'],
            ['name' => 'Kanya Caya', 'nickname' => 'Kanya', 'birth_place' => 'Daerah Istimewa Yogyakarta', 'birth_date' => '2004-11-22', 'gen' => '7', 'join_date' => '2018-09-29', 'status' => 'Lulus', 'graduation_date' => '2018-10-06', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Mutiara Azzahra', 'nickname' => 'Muthe', 'birth_place' => 'Bandung', 'birth_date' => '2004-07-12', 'gen' => '7', 'join_date' => '2018-09-29', 'status' => 'Aktif', 'restructure_status' => 'Masih Aktif (Masuk Sebelum Restrukturisasi)'],
            ['name' => 'Nabila Fitriana', 'nickname' => 'Lala', 'birth_place' => 'Bandar Lampung', 'birth_date' => '2000-12-29', 'gen' => '7', 'join_date' => '2018-09-29', 'status' => 'Lulus', 'graduation_date' => '2021-03-14', 'restructure_status' => 'Lulus Terkena Restrukturisasi'],
            ['name' => 'Rifa Fatmasari', 'nickname' => 'Rifa', 'birth_place' => 'Jakarta', 'birth_date' => '2000-05-10', 'gen' => '7', 'join_date' => '2018-09-29', 'status' => 'Lulus', 'graduation_date' => '2019-09-13', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Viona Fadrin', 'nickname' => 'Vivi', 'birth_place' => 'Jakarta', 'birth_date' => '2000-11-08', 'gen' => '7', 'join_date' => '2018-09-29', 'status' => 'Lulus', 'graduation_date' => '2021-03-12', 'restructure_status' => 'Lulus Terkena Restrukturisasi'],
            ['name' => 'Yessica Tamara', 'nickname' => 'Chika', 'birth_place' => 'Medan', 'birth_date' => '2002-09-24', 'gen' => '7', 'join_date' => '2018-09-29', 'status' => 'Lulus', 'graduation_announce_date' => '2023-09-28', 'graduation_announce_event' => 'Aturan Anti Cinta', 'graduation_date' => '2024-01-20', 'restructure_status' => 'Lulus Setelah Restrukturisasi'],

            // Generasi 8
            ['name' => 'Amanina Afiqah', 'nickname' => 'Afiqah', 'birth_place' => 'Jakarta', 'birth_date' => '2006-01-06', 'gen' => '8', 'join_date' => '2019-04-27', 'status' => 'Lulus', 'promotion_date' => '2020-08-22', 'graduation_date' => '2021-03-14', 'restructure_status' => 'Lulus Terkena Restrukturisasi'],
            ['name' => 'Amirah Fatin', 'nickname' => 'Amira', 'birth_place' => 'Denpasar', 'birth_date' => '2000-10-12', 'gen' => '8', 'join_date' => '2019-04-27', 'status' => 'Lulus', 'promotion_date' => '2020-08-22', 'graduation_announce_date' => '2021-10-22', 'graduation_announce_event' => 'Aturan Anti Cinta', 'graduation_date' => '2021-11-27', 'restructure_status' => 'Lulus Setelah Restrukturisasi'],
            ['name' => 'Cindy Nugroho', 'nickname' => 'Nunu', 'birth_place' => 'Jakarta', 'birth_date' => '2007-06-09', 'gen' => '8', 'join_date' => '2019-04-27', 'status' => 'Lulus', 'graduation_date' => '2021-03-11', 'restructure_status' => 'Lulus Terkena Restrukturisasi'],
            ['name' => 'Cornelia Vanisa', 'nickname' => 'Oniel', 'birth_place' => 'Tangerang', 'birth_date' => '2002-07-26', 'gen' => '8', 'join_date' => '2019-04-27', 'status' => 'Aktif', 'promotion_date' => '2020-08-22', 'restructure_status' => 'Masih Aktif (Masuk Sebelum Restrukturisasi)'],
            ['name' => 'Devytha Maharani Putri', 'nickname' => 'Devytha', 'birth_place' => 'Denpasar', 'birth_date' => '2002-11-22', 'gen' => '8', 'join_date' => '2019-04-27', 'status' => 'Lulus', 'graduation_date' => '2020-03-30', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Eriena Kartika Dewi', 'nickname' => 'Eri-chan', 'birth_place' => 'Jakarta', 'birth_date' => '2003-04-18', 'gen' => '8', 'join_date' => '2019-04-27', 'status' => 'Lulus', 'graduation_date' => '2020-05-16', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Fiony Alveria', 'nickname' => 'Fiony', 'birth_place' => 'Jakarta', 'birth_date' => '2002-02-04', 'gen' => '8', 'join_date' => '2019-04-27', 'status' => 'Aktif', 'promotion_date' => '2020-08-22', 'restructure_status' => 'Masih Aktif (Masuk Sebelum Restrukturisasi)'],
            ['name' => 'Flora Shafiq', 'nickname' => 'Flora', 'birth_place' => 'Tangerang', 'birth_date' => '2005-04-04', 'gen' => '8', 'join_date' => '2019-04-27', 'status' => 'Lulus', 'promotion_date' => '2020-08-22', 'graduation_date' => '2025-03-05', 'restructure_status' => 'Lulus Setelah Restrukturisasi'],
            ['name' => 'Gabriella Stevany', 'nickname' => 'Vany', 'birth_place' => 'Jakarta', 'birth_date' => '2002-05-22', 'gen' => '8', 'join_date' => '2019-04-27', 'status' => 'Lulus', 'graduation_date' => '2021-03-11', 'restructure_status' => 'Lulus Terkena Restrukturisasi'],
            ['name' => 'Iris Vevina Prasetio', 'nickname' => 'Iris', 'birth_place' => '', 'birth_date' => '2003-08-05', 'gen' => '8', 'join_date' => '2019-04-27', 'status' => 'Lulus', 'graduation_date' => '2019-12-30', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Keisya Ramadhani', 'nickname' => 'Keisya', 'birth_place' => 'Jakarta', 'birth_date' => '2004-11-10', 'gen' => '8', 'join_date' => '2019-04-27', 'status' => 'Lulus', 'graduation_date' => '2021-03-11', 'restructure_status' => 'Lulus Terkena Restrukturisasi'],
            ['name' => 'Lulu Salsabila', 'nickname' => 'Lulu', 'birth_place' => 'Serang', 'birth_date' => '2002-10-23', 'gen' => '8', 'join_date' => '2019-04-27', 'status' => 'Aktif', 'promotion_date' => '2020-08-22', 'restructure_status' => 'Masih Aktif (Masuk Sebelum Restrukturisasi)'],
            ['name' => 'Nyimas Ratu Rafa', 'nickname' => 'Ratu', 'birth_place' => 'Kota Tangerang', 'birth_date' => '2005-07-01', 'gen' => '8', 'join_date' => '2019-04-27', 'status' => 'Lulus', 'promotion_date' => '2020-08-22', 'graduation_date' => '2020-11-09', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Pamela Krysanthe Adijaya', 'nickname' => 'Pamela', 'birth_place' => 'Jakarta', 'birth_date' => '2003-10-03', 'gen' => '8', 'join_date' => '2019-04-27', 'status' => 'Lulus', 'graduation_date' => '2020-02-07', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Reva Adriana Ramadhani', 'nickname' => 'Reva', 'birth_place' => 'Jakarta', 'birth_date' => '2004-11-03', 'gen' => '8', 'join_date' => '2019-04-27', 'status' => 'Lulus', 'graduation_date' => '2019-12-30', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Reva Fidela', 'nickname' => 'Adel', 'birth_place' => 'Jakarta', 'birth_date' => '2006-07-14', 'gen' => '8', 'join_date' => '2019-04-27', 'status' => 'Lulus', 'promotion_date' => '2020-08-22', 'graduation_announce_date' => '2024-06-06', 'graduation_announce_event' => 'Aturan Anti Cinta', 'graduation_date' => '2024-10-12', 'restructure_status' => 'Lulus Setelah Restrukturisasi'],
            ['name' => 'Salma Annisa', 'nickname' => 'Alma', 'birth_place' => 'Jakarta', 'birth_date' => '2000-08-16', 'gen' => '8', 'join_date' => '2019-04-27', 'status' => 'Lulus', 'graduation_date' => '2020-09-01', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Umega Maulana', 'nickname' => 'Ume', 'birth_place' => 'Jakarta', 'birth_date' => '2004-03-27', 'gen' => '8', 'join_date' => '2019-04-27', 'status' => 'Lulus', 'promotion_date' => '2020-08-22', 'graduation_date' => '2021-03-12', 'restructure_status' => 'Lulus Terkena Restrukturisasi'],
            ['name' => 'Zahra Nur', 'nickname' => 'Ara', 'birth_place' => 'Garut', 'birth_date' => '2003-08-05', 'gen' => '8', 'join_date' => '2019-04-27', 'status' => 'Lulus', 'promotion_date' => '2020-08-22', 'graduation_date' => '2021-08-25', 'restructure_status' => 'Lulus Setelah Restrukturisasi'],

            // Generasi 9
            ['name' => 'Adzana Shaliha', 'nickname' => 'Ashel', 'birth_place' => 'Jakarta', 'birth_date' => '2005-01-08', 'gen' => '9', 'join_date' => '2019-12-01', 'status' => 'Lulus', 'promotion_date' => '2021-03-12', 'graduation_announce_date' => '2023-10-12', 'graduation_announce_event' => 'Cara Meminum Ramune', 'graduation_date' => '2024-02-11', 'restructure_status' => 'Lulus Setelah Restrukturisasi'],
            ['name' => 'Caithlyn Gwyneth', 'nickname' => 'Caithlyn', 'birth_place' => 'Jakarta', 'birth_date' => '2009-03-26', 'gen' => '9', 'join_date' => '2019-12-01', 'status' => 'Lulus', 'graduation_date' => '2021-03-11', 'restructure_status' => 'Lulus Terkena Restrukturisasi'],
            ['name' => 'Chalista Ellysia', 'nickname' => 'Chalista', 'birth_place' => 'Sidoarjo', 'birth_date' => '2006-03-01', 'gen' => '9', 'join_date' => '2019-12-01', 'status' => 'Lulus', 'graduation_date' => '2021-03-11', 'restructure_status' => 'Lulus Terkena Restrukturisasi'],
            ['name' => 'Christabel Jocelyn', 'nickname' => 'Abel', 'birth_place' => 'Surabaya', 'birth_date' => '2007-08-17', 'gen' => '9', 'join_date' => '2019-12-01', 'status' => 'Lulus', 'graduation_date' => '2021-03-11', 'restructure_status' => 'Lulus Terkena Restrukturisasi'],
            ['name' => 'Indah Cahya', 'nickname' => 'Indah', 'birth_place' => 'Jambi', 'birth_date' => '2001-03-20', 'gen' => '9', 'join_date' => '2019-12-01', 'status' => 'Aktif', 'promotion_date' => '2021-03-12', 'restructure_status' => 'Masih Aktif (Masuk Sebelum Restrukturisasi)'],
            ['name' => 'Kathrina Irene', 'nickname' => 'Kathrina', 'birth_place' => 'Bekasi', 'birth_date' => '2006-07-26', 'gen' => '9', 'join_date' => '2019-12-01', 'status' => 'Aktif', 'promotion_date' => '2021-03-12', 'restructure_status' => 'Masih Aktif (Masuk Sebelum Restrukturisasi)'],
            ['name' => 'Lian Olivia Payten', 'nickname' => 'Olivia', 'birth_place' => 'Kota Tangerang', 'birth_date' => '2003-10-13', 'gen' => '9', 'join_date' => '2019-12-01', 'status' => 'Lulus', 'graduation_date' => '2020-02-17', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Marsha Lenathea', 'nickname' => 'Marsha', 'birth_place' => 'Jakarta', 'birth_date' => '2006-01-09', 'gen' => '9', 'join_date' => '2019-12-01', 'status' => 'Aktif', 'promotion_date' => '2021-03-12', 'restructure_status' => 'Masih Aktif (Masuk Sebelum Restrukturisasi)'],
            ['name' => 'Nabila Gusmarlia', 'nickname' => 'Nabila', 'birth_place' => 'Jakarta', 'birth_date' => '2005-06-22', 'gen' => '9', 'join_date' => '2019-12-01', 'status' => 'Lulus', 'graduation_date' => '2021-03-11', 'restructure_status' => 'Lulus Terkena Restrukturisasi'],
            ['name' => 'Putri Elzahra', 'nickname' => 'Zahra', 'birth_place' => 'Depok', 'birth_date' => '2006-05-19', 'gen' => '9', 'join_date' => '2019-12-01', 'status' => 'Lulus', 'graduation_date' => '2021-03-11', 'restructure_status' => 'Lulus Terkena Restrukturisasi'],
            ['name' => 'Shinta Devi', 'nickname' => 'Shinta', 'birth_place' => 'Tangerang', 'birth_date' => '2004-06-07', 'gen' => '9', 'join_date' => '2019-12-01', 'status' => 'Lulus', 'graduation_date' => '2021-03-11', 'restructure_status' => 'Lulus Terkena Restrukturisasi'],
            ['name' => 'Tiara Sasi Kirana Putri', 'nickname' => 'Tiara', 'birth_place' => 'Jakarta', 'birth_date' => '2001-03-29', 'gen' => '9', 'join_date' => '2019-12-01', 'status' => 'Lulus', 'graduation_date' => '2020-02-17', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],

            // Generasi 10
            ['name' => 'Abieza Syabira', 'nickname' => 'Abieza', 'birth_place' => 'Kota Tangerang', 'birth_date' => '2002-04-05', 'gen' => '10', 'join_date' => '2020-08-27', 'status' => 'Lulus', 'graduation_date' => '2020-12-04', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Alia Giselle Maharani', 'nickname' => 'Giselle', 'birth_place' => 'Kota Tangerang', 'birth_date' => '2006-12-20', 'gen' => '10', 'join_date' => '2020-08-27', 'status' => 'Lulus', 'cancelled_date' => '2020-12-04', 'rejoin_date' => '2021-12-18', 'graduation_date' => '2023-04-03', 'restructure_status' => 'Lulus (Generasi 10)'],
            ['name' => 'Amanda Puspita Sukma Mulyadewi', 'nickname' => 'Amanda', 'birth_place' => 'Kota Malang', 'birth_date' => '2004-12-17', 'gen' => '10', 'join_date' => '2020-08-27', 'status' => 'Aktif', 'cancelled_date' => '2020-12-04', 'rejoin_date' => '2021-12-18', 'promotion_date' => '2023-05-08', 'restructure_status' => 'Masih Aktif (Khusus Generasi 10)'],
            ['name' => 'Aurellia', 'nickname' => 'Lia', 'birth_place' => 'Jakarta', 'birth_date' => '2002-10-29', 'gen' => '10', 'join_date' => '2020-08-27', 'status' => 'Aktif', 'cancelled_date' => '2020-12-04', 'rejoin_date' => '2021-12-18', 'promotion_date' => '2023-05-08', 'restructure_status' => 'Masih Aktif (Khusus Generasi 10)'],
            ['name' => 'Callista Alifia Wardhana', 'nickname' => 'Callie', 'birth_place' => 'Jakarta', 'birth_date' => '2005-08-08', 'gen' => '10', 'join_date' => '2020-08-27', 'status' => 'Lulus', 'cancelled_date' => '2020-12-04', 'rejoin_date' => '2021-12-18', 'promotion_date' => '2023-05-08', 'graduation_date' => '2024-12-20', 'restructure_status' => 'Lulus (Generasi 10)'],
            ['name' => 'Danessa Valerie Hertanto', 'nickname' => 'Danessa', 'birth_place' => 'Depok', 'birth_date' => '2002-04-04', 'gen' => '10', 'join_date' => '2020-08-27', 'status' => 'Lulus', 'graduation_date' => '2020-12-04', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Gabriela Abigail Mewengkang', 'nickname' => 'Ella', 'birth_place' => 'Jakarta', 'birth_date' => '2006-08-07', 'gen' => '10', 'join_date' => '2020-08-27', 'status' => 'Aktif', 'cancelled_date' => '2020-12-04', 'rejoin_date' => '2021-12-18', 'promotion_date' => '2023-05-08', 'restructure_status' => 'Masih Aktif (Khusus Generasi 10)'],
            ['name' => 'Indira Putri Seruni', 'nickname' => 'Indira', 'birth_place' => 'Bandung', 'birth_date' => '2004-04-26', 'gen' => '10', 'join_date' => '2020-08-27', 'status' => 'Lulus', 'cancelled_date' => '2020-12-04', 'rejoin_date' => '2021-12-18', 'promotion_date' => '2023-05-08', 'graduation_announce_date' => '2025-04-26', 'graduation_announce_event' => 'Aturan Anti Cinta', 'graduation_date' => '2025-09-12', 'restructure_status' => 'Lulus (Generasi 10)'],
            ['name' => 'Jesslyn Elly', 'nickname' => 'Lyn', 'birth_place' => 'Jakarta', 'birth_date' => '2001-09-13', 'gen' => '10', 'join_date' => '2020-08-27', 'status' => 'Aktif', 'cancelled_date' => '2020-12-04', 'rejoin_date' => '2021-12-18', 'promotion_date' => '2023-05-08', 'restructure_status' => 'Masih Aktif (Khusus Generasi 10)'],
            ['name' => 'Naura Safinatunnajah', 'nickname' => 'Naura', 'birth_place' => 'Jakarta', 'birth_date' => '2003-08-20', 'gen' => '10', 'join_date' => '2020-08-27', 'status' => 'Lulus', 'graduation_date' => '2020-12-04', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Raisha Syifa Wardhana', 'nickname' => 'Raisha', 'birth_place' => 'Jakarta', 'birth_date' => '2007-11-11', 'gen' => '10', 'join_date' => '2020-08-27', 'status' => 'Aktif', 'cancelled_date' => '2020-12-04', 'rejoin_date' => '2021-12-18', 'promotion_date' => '2023-05-08', 'restructure_status' => 'Masih Aktif (Khusus Generasi 10)'],

            // Generasi 11
            ['name' => 'Alya Amanda Fatihah', 'nickname' => 'Alya', 'birth_place' => '', 'birth_date' => '2006-08-26', 'gen' => '11', 'join_date' => '2022-10-31', 'status' => 'Aktif', 'graduation_announce_date' => '2024-11-01', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],
            ['name' => 'Anindya Ramadhani Purnomo', 'nickname' => 'Anindya', 'birth_place' => '', 'birth_date' => '2005-10-18', 'gen' => '11', 'join_date' => '2022-10-31', 'status' => 'Aktif', 'graduation_announce_date' => '2024-11-01', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],
            ['name' => 'Aulia Asyira Basarestu', 'nickname' => 'Aulia', 'birth_place' => '', 'birth_date' => '2007-01-19', 'gen' => '11', 'join_date' => '2022-10-31', 'status' => 'Lulus', 'graduation_date' => '2023-04-03', 'restructure_status' => 'Lulus dan Masuk Setelah Restrukturisasi'],
            ['name' => 'Cathleen Hana Nixie', 'nickname' => 'Cathy', 'birth_place' => '', 'birth_date' => '2009-05-28', 'gen' => '11', 'join_date' => '2022-10-31', 'status' => 'Aktif', 'graduation_announce_date' => '2024-11-01', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],
            ['name' => 'Celline Thefannie', 'nickname' => 'Elin', 'birth_place' => '', 'birth_date' => '2007-04-09', 'gen' => '11', 'join_date' => '2022-10-31', 'status' => 'Aktif', 'graduation_announce_date' => '2024-11-01', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],
            ['name' => 'Chelsea Davina Norman', 'nickname' => 'Chelsea', 'birth_place' => '', 'birth_date' => '2009-12-23', 'gen' => '11', 'join_date' => '2022-10-31', 'status' => 'Aktif', 'graduation_announce_date' => '2024-11-01', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],
            ['name' => 'Cynthia Yaputera', 'nickname' => 'Cynthia', 'birth_place' => '', 'birth_date' => '2003-11-22', 'gen' => '11', 'join_date' => '2022-10-31', 'status' => 'Aktif', 'graduation_announce_date' => '2024-11-01', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],
            ['name' => 'Dena Natalia Ang', 'nickname' => 'Danella', 'birth_place' => '', 'birth_date' => '2005-12-16', 'gen' => '11', 'join_date' => '2022-10-31', 'status' => 'Aktif', 'graduation_announce_date' => '2024-11-01', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],
            ['name' => 'Desy Natalia Ang', 'nickname' => 'Daisy', 'birth_place' => '', 'birth_date' => '2005-12-16', 'gen' => '11', 'join_date' => '2022-10-31', 'status' => 'Aktif', 'graduation_announce_date' => '2024-11-01', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],
            ['name' => 'Gendis Mayrannisa Setiawan', 'nickname' => 'Gendis', 'birth_place' => '', 'birth_date' => '2010-06-23', 'gen' => '11', 'join_date' => '2022-10-31', 'status' => 'Aktif', 'graduation_announce_date' => '2024-11-01', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],
            ['name' => 'Grace Octaviani Tanujaya', 'nickname' => 'Gracie', 'birth_place' => '', 'birth_date' => '2007-10-18', 'gen' => '11', 'join_date' => '2022-10-31', 'status' => 'Aktif', 'graduation_announce_date' => '2024-02-01', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],
            ['name' => 'Greesella Sophina Adhalia', 'nickname' => 'Greesel', 'birth_place' => '', 'birth_date' => '2006-01-10', 'gen' => '11', 'join_date' => '2022-10-31', 'status' => 'Aktif', 'graduation_announce_date' => '2024-02-01', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],
            ['name' => 'Jeane Victoria Kurniawan', 'nickname' => 'Jeane', 'birth_place' => '', 'birth_date' => '2006-06-05', 'gen' => '11', 'join_date' => '2022-10-31', 'status' => 'Lulus', 'graduation_date' => '2024-05-22', 'restructure_status' => 'Lulus dan Masuk Setelah Restrukturisasi'],
            ['name' => 'Michelle Alexandra Suandi', 'nickname' => 'Michie', 'birth_place' => '', 'birth_date' => '2009-04-22', 'gen' => '11', 'join_date' => '2022-10-31', 'status' => 'Aktif', 'graduation_announce_date' => '2024-11-01', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],

            // Generasi 12
            ['name' => 'Abigail Rachel Lie', 'nickname' => 'Aralie', 'birth_place' => '', 'birth_date' => '2008-08-06', 'gen' => '12', 'join_date' => '2023-11-18', 'status' => 'Aktif', 'promotion_date' => '2026-01-01', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],
            ['name' => 'Adeline Wijaya', 'nickname' => 'Delynn', 'birth_place' => '', 'birth_date' => '2007-09-01', 'gen' => '12', 'join_date' => '2023-11-18', 'status' => 'Aktif', 'promotion_date' => '2026-01-01', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],
            ['name' => 'Aisa Maharani Napitupulu', 'nickname' => 'Shasa', 'birth_place' => '', 'birth_date' => '2006-01-31', 'gen' => '12', 'join_date' => '2023-11-18', 'status' => 'Lulus', 'graduation_date' => '2024-06-26', 'restructure_status' => 'Lulus dan Masuk Setelah Restrukturisasi'],
            ['name' => 'Aurhel Alana Tirta', 'nickname' => 'Lana', 'birth_place' => '', 'birth_date' => '2006-09-14', 'gen' => '12', 'join_date' => '2023-11-18', 'status' => 'Aktif', 'promotion_date' => '2025-05-01', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],
            ['name' => 'Catherina Vallencia Kurniawan', 'nickname' => 'Erine', 'birth_place' => '', 'birth_date' => '2007-08-21', 'gen' => '12', 'join_date' => '2023-11-18', 'status' => 'Aktif', 'promotion_date' => '2026-01-01', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],
            ['name' => 'Fritzy Rosmerian', 'nickname' => 'Fritzy', 'birth_place' => '', 'birth_date' => '2008-07-28', 'gen' => '12', 'join_date' => '2023-11-18', 'status' => 'Aktif', 'promotion_date' => '2025-05-01', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],
            ['name' => 'Hillary Abigail', 'nickname' => 'Lily', 'birth_place' => '', 'birth_date' => '2007-10-19', 'gen' => '12', 'join_date' => '2023-11-18', 'status' => 'Aktif', 'promotion_date' => '2026-01-01', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],
            ['name' => 'Jazzlyn Agatha Trisha', 'nickname' => 'Trisha', 'birth_place' => '', 'birth_date' => '2011-02-16', 'gen' => '12', 'join_date' => '2023-11-18', 'status' => 'Aktif', 'promotion_date' => '2026-01-01', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],
            ['name' => 'Letycia Moreen Praditya', 'nickname' => 'Moreen', 'birth_place' => '', 'birth_date' => '2010-06-07', 'gen' => '12', 'join_date' => '2023-11-18', 'status' => 'Lulus', 'graduation_date' => '2025-05-01', 'restructure_status' => 'Lulus dan Masuk Setelah Restrukturisasi'],
            ['name' => 'Michelle Levia Arifin', 'nickname' => 'Levi', 'birth_place' => '', 'birth_date' => '2009-01-24', 'gen' => '12', 'join_date' => '2023-11-18', 'status' => 'Aktif', 'promotion_date' => '2026-01-01', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],
            ['name' => 'Nayla Suji Aurelia', 'nickname' => 'Nayla', 'birth_place' => '', 'birth_date' => '2007-06-18', 'gen' => '12', 'join_date' => '2023-11-18', 'status' => 'Aktif', 'promotion_date' => '2026-01-01', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],
            ['name' => 'Nina Tutachia Chapman', 'nickname' => 'Nachia', 'birth_place' => '', 'birth_date' => '2009-10-16', 'gen' => '12', 'join_date' => '2023-11-18', 'status' => 'Aktif', 'promotion_date' => '2026-01-01', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],
            ['name' => 'Oline Manuel Chay', 'nickname' => 'Oline', 'birth_place' => '', 'birth_date' => '2007-11-03', 'gen' => '12', 'join_date' => '2023-11-18', 'status' => 'Aktif', 'promotion_date' => '2026-01-01', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],
            ['name' => 'Regina Wilian Hapsari', 'nickname' => 'Regie', 'birth_place' => '', 'birth_date' => '2009-12-10', 'gen' => '12', 'join_date' => '2023-11-18', 'status' => 'Lulus', 'graduation_announce_date' => '2025-08-14', 'graduation_date' => '2025-08-18', 'restructure_status' => 'Lulus dan Masuk Setelah Restrukturisasi'],
            ['name' => 'Ribka Budiman', 'nickname' => 'Ribka', 'birth_place' => '', 'birth_date' => '2009-01-13', 'gen' => '12', 'join_date' => '2023-11-18', 'status' => 'Aktif', 'promotion_date' => '2026-01-01', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],
            ['name' => 'Shabilqis Naila Bustomi', 'nickname' => 'Nala', 'birth_place' => '', 'birth_date' => '2008-09-01', 'gen' => '12', 'join_date' => '2023-11-18', 'status' => 'Aktif', 'promotion_date' => '2026-01-01', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],
            ['name' => 'Victoria Kimberly Lukitama', 'nickname' => 'Kimmy', 'birth_place' => '', 'birth_date' => '2010-03-08', 'gen' => '12', 'join_date' => '2023-11-18', 'status' => 'Aktif', 'promotion_date' => '2026-01-01', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],

            // Generasi 13
            ['name' => 'Astrella Virgiananda Nugraha', 'nickname' => 'Virgi', 'birth_place' => '', 'birth_date' => '2010-08-06', 'gen' => '13', 'join_date' => '2024-10-31', 'status' => 'Aktif', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],
            ['name' => 'Aulia Riza Firdausy Effendi', 'nickname' => 'Riza', 'birth_place' => '', 'birth_date' => '2007-07-14', 'gen' => '13', 'join_date' => '2024-10-31', 'status' => 'Aktif', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],
            ['name' => 'Bong Aprilli Paskah', 'nickname' => 'Rilly', 'birth_place' => '', 'birth_date' => '2010-04-01', 'gen' => '13', 'join_date' => '2024-10-31', 'status' => 'Aktif', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],
            ['name' => 'Hagia Sopia', 'nickname' => 'Giaa', 'birth_place' => '', 'birth_date' => '2008-07-01', 'gen' => '13', 'join_date' => '2024-10-31', 'status' => 'Aktif', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],
            ['name' => 'Humaira Ramadhani Salfiandi', 'nickname' => 'Maira', 'birth_place' => '', 'birth_date' => '2011-08-13', 'gen' => '13', 'join_date' => '2024-10-31', 'status' => 'Aktif', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],
            ['name' => 'Jacqueline Immanuela Jonathan', 'nickname' => 'Ekin', 'birth_place' => '', 'birth_date' => '2009-07-09', 'gen' => '13', 'join_date' => '2024-10-31', 'status' => 'Aktif', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],
            ['name' => 'Jemima Evodie Mayra Lijaya', 'nickname' => 'Jemima', 'birth_place' => '', 'birth_date' => '2009-11-09', 'gen' => '13', 'join_date' => '2024-10-31', 'status' => 'Aktif', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],
            ['name' => 'Mikaela Kusjanto', 'nickname' => 'Mikaela', 'birth_place' => '', 'birth_date' => '2007-12-15', 'gen' => '13', 'join_date' => '2024-10-31', 'status' => 'Aktif', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],
            ['name' => 'Nur Intan', 'nickname' => 'Intan', 'birth_place' => '', 'birth_date' => '2006-02-24', 'gen' => '13', 'join_date' => '2024-10-31', 'status' => 'Aktif', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],

            // Kaigai 1
            ['name' => 'Aki Takajo', 'nickname' => 'Akicha', 'birth_place' => 'Tokyo', 'birth_date' => '1991-10-03', 'gen' => 'Kaigai 1', 'join_date' => '2012-11-01', 'status' => 'Lulus', 'promotion_date' => '2012-12-23', 'graduation_date' => '2014-04-24', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],
            ['name' => 'Haruka Nakagawa', 'nickname' => 'Haruka', 'birth_place' => 'Tokyo', 'birth_date' => '1992-02-10', 'gen' => 'Kaigai 1', 'join_date' => '2012-11-01', 'status' => 'Lulus', 'promotion_date' => '2012-12-23', 'graduation_announce_date' => '2016-02-27', 'graduation_announce_event' => 'JKT48 Request Hour Setlist Best 30 2016', 'graduation_date' => '2016-12-30', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],

            // Kaigai 2
            ['name' => 'Rina Chikano', 'nickname' => 'Chikarina', 'birth_place' => 'Tokyo', 'birth_date' => '1993-04-23', 'gen' => 'Kaigai 2', 'join_date' => '2014-04-24', 'status' => 'Lulus', 'graduation_announce_date' => '2017-12-09', 'graduation_announce_event' => 'Team KIII B•E•L•I•E•V•E Show', 'graduation_date' => '2018-03-25', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],

            // Transfer
            ['name' => 'Saya Kawamoto', 'nickname' => 'Sayaya', 'birth_place' => 'Betsukai', 'birth_date' => '1998-08-31', 'gen' => 'Transfer', 'join_date' => '2018-09-17', 'status' => 'Lulus', 'graduation_date' => '2018-10-19', 'restructure_status' => 'Lulus Sebelum Restrukturisasi'],

            // V1
            ['name' => 'Kanaia Asa', 'nickname' => 'Kanaia', 'birth_place' => '', 'birth_date' => '2000-03-01', 'gen' => 'V1', 'join_date' => '2023-07-30', 'status' => 'Lulus', 'graduation_announce_date' => '2025-05-05', 'graduation_date' => '2025-05-31', 'restructure_status' => 'Lulus dan Masuk Setelah Restrukturisasi'],
            ['name' => 'Tana Nona', 'nickname' => 'Tana', 'birth_place' => '', 'birth_date' => '2000-07-30', 'gen' => 'V1', 'join_date' => '2023-07-30', 'status' => 'Aktif', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],
            ['name' => 'Pia Meraleo', 'nickname' => 'Pia', 'birth_place' => '', 'birth_date' => '2000-04-22', 'gen' => 'V1', 'join_date' => '2023-07-30', 'status' => 'Aktif', 'restructure_status' => 'Masih Aktif (Masuk Setelah Restrukturisasi)'],

            // V2
            ['name' => 'Isha Kirana', 'nickname' => '', 'birth_place' => '', 'birth_date' => null, 'gen' => 'V2', 'join_date' => null, 'status' => 'Aktif'],
            ['name' => 'Maura Nilambari', 'nickname' => '', 'birth_place' => '', 'birth_date' => null, 'gen' => 'V2', 'join_date' => null, 'status' => 'Aktif'],
            ['name' => 'Sami Maono', 'nickname' => '', 'birth_place' => '', 'birth_date' => null, 'gen' => 'V2', 'join_date' => null, 'status' => 'Aktif'],
        ];

        $count = 0;
        foreach ($members as $data) {
            $genCode = $data['gen'];
            unset($data['gen']);

            if (! isset($genMap[$genCode])) {
                continue;
            }

            $data['generation_id'] = $genMap[$genCode];

            Member::updateOrCreate(
                ['name' => $data['name']],
                $data
            );
            $count++;
        }

        $this->command->info("Seeded {$count} members.");
    }
}
