---
exclude_paths:
  - "vendor/**"
  - "node_modules/**"
  - "storage/**"
  - "bootstrap/cache/**"
  - "public/build/**"
  - "package-lock.json"
  - "composer.lock"
  - "database/migrations/**"
  - "database/seeders/**"
  - "config/**"
  - "bootstrap/**"
  - "CHANGELOG.md"
  - "public/css/**"
  - "resources/css/**"
